// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraYnBMFuilXhiMqClF2JJt02UxRYjG-Q',
    appId: '1:433731039140:web:e6d8695a26bdbc03c91b31',
    messagingSenderId: '433731039140',
    projectId: 'boardmate-app',
    authDomain: 'boardmate-app.firebaseapp.com',
    storageBucket: 'boardmate-app.firebasestorage.app',
    measurementId: 'G-NNQVQGEW9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XIam5bghSexAV7w6IPlwNFulv5Gv03k',
    appId: '1:433731039140:android:220de043f02f5ad0c91b31',
    messagingSenderId: '433731039140',
    projectId: 'boardmate-app',
    storageBucket: 'boardmate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXWQE2fo-7ZMU9iv00G22rDh7ROPgjbPI',
    appId: '1:433731039140:ios:86052b00e3959f8ec91b31',
    messagingSenderId: '433731039140',
    projectId: 'boardmate-app',
    storageBucket: 'boardmate-app.firebasestorage.app',
    androidClientId: '433731039140-cja9feklc402mljei44omf785m0gk2rm.apps.googleusercontent.com',
    iosClientId: '433731039140-7nv19iai74kt2fj6tu5lvmtfugb820gn.apps.googleusercontent.com',
    iosBundleId: 'com.board.game.boardmate',
  );

}